# Generated by Django 5.1.3 on 2024-11-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("titulo_largo", models.CharField(max_length=255)),
                ("precio_base", models.IntegerField()),
                ("imagen", models.ImageField(upload_to="eventos/")),
            ],
        ),
    ]
