# Generated by Django 5.1.3 on 2024-11-28 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="descripcion",
            field=models.TextField(default="more info..."),
        ),
        migrations.AddField(
            model_name="evento",
            name="fecha_fin",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="evento",
            name="fecha_inicio",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
