# Generated by Django 5.1.3 on 2024-11-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_evento_descripcion_evento_fecha_fin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="precio_base",
            new_name="precio",
        ),
    ]
