# Generated by Django 5.1.3 on 2024-11-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0003_rename_precio_base_evento_precio"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="codigo_i3a",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
