# Generated by Django 5.1.3 on 2024-12-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0004_evento_codigo_i3a"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="precio",
        ),
    ]
