# Generated by Django 5.1.3 on 2024-12-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0005_remove_evento_precio"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="activo",
            field=models.BooleanField(default=False),
        ),
    ]
