# Generated by Django 5.1.3 on 2024-12-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0006_evento_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="web",
            field=models.TextField(default="#"),
        ),
    ]
